### PR TITLE
Translation on both DEV and PROD

### PR DESCRIPTION
**Pull request by crayner**

### CODE REVIEW

**Comment by Ex3v** [comment]
That's another approach, but I still can't seem to understand this change. `TranslatorInterface` along with strict typing contracts passing only right classes anyway. Why throwing generic exception instead?

**Comment by crayner** [comment]
In Development it throws an error.  In production works fine.

------------------------------------------
I greet you with the great words,
Grace and Peace

Craig Rayner
craig@craigrayner.com
Phone: +61 2 6352 5571
Mobile: +61 456 560 018

**Comment by Ex3v** [comment]
So here's your answer - `display_errors` and `error_reporting` ;) I'd stay with strict interface in constructor - safer, more standarized. 
Best way is to use Symfony's error handler, and service like Sentry to get all errors your code produce.

**Comment by crayner** [comment]
Happy for you to do that if necessary....

------------------------------------------
I greet you with the great words,
Grace and Peace

Craig Rayner
craig@craigrayner.com
Phone: +61 2 6352 5571
Mobile: +61 456 560 018

**Comment by crayner** [comment]
Closed for correction to Translation Hint.

**Pull request closed without merging**
